version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '50001:8025'

    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - './backend:/application'
            - ./backend/postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=symfony5
            - POSTGRES_PASSWORD=symfony5
            - POSTGRES_DB=symfony5
        ports:
            - '50004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './backend:/application'
            - './frontend:/frontend'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '50000:80'

    php-fpm:
        build: ./docker/php-fpm
#        working_dir: /application
        volumes:
            - './backend:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'

    node:
        build: ./docker/node
        working_dir: /frontend
        volumes:
            - './frontend:/frontend'
        ports:
            - '50005:3000'
        command: npm start
