# docker/node/Dockerfile
FROM node:16-alpine

# Create app directory
WORKDIR /frontend
#
## Install app dependencies
#COPY package*.json ./
#
#RUN npm install
#
## Bundle app source
#COPY . .
#
## Expose the port the app runs on
#EXPOSE 3000
#
## Start the app
#CMD ["npm", "start"]
